### ISSUE TITLE
[bugfix] ML Commons Agent Framework

### ISSUE THREAD

**Issue by tkykenmt** [tkykenmt/opensearch-feature-explorer#3028]
## Overview
- Version: v3.1.0
- Category: bugfix
- Repositories: ml-commons
- PRs: 18

## Pull Requests
| PR | Title | Category | Repository |
|-----|-------|----------|------------|
| `https://github.com/opensearch-project/ml-commons/pull/3874` | Support persisting MCP tools in system index | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3884` | [Agent] PlanExecuteReflect: Return memory early to track pro... | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3786` | Add space type mapping for pre-trained embedding models, add... | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3810` | Support customized message endpoint and addressing comments | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3891` | Add custom SSE endpoint for the MCP Client | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3820` | Expose Update Agent API | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3888` | Use function calling for existing LLM interfaces | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3845` | Add error handling for plan&execute agent | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3661` | Metrics framework integration with ml-commons | enhancement | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3862` | Fix connector private IP validation when executing agent wit... | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3882` | For inline model connector name isn't required | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3852` | Fix the tutorial in AIConnectorHelper when fetching domain\_... | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3856` | Adds Json Parsing to nested object during update Query step ... | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3854` | Adding / as a valid character | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3844` | Quick fix for guava noclass issue | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3822` | Fix python client not able to connect to MCP server issue | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3814` | Excluding circuit breaker for Agent | bugfix | ml-commons |
| `https://github.com/opensearch-project/ml-commons/pull/3837` | Adding tenantId to the connector executor when this is inlin... | bugfix | ml-commons |

## Tasks
- [ ] Investigate PRs
- [ ] Create release report: `docs/releases/v3.1.0/features/ml-commons-agent-framework.md`
- [ ] Update feature report: `docs/features/ml-commons-agent-framework.md`

**Comment by tkykenmt** [comment]
## Investigation Complete

### Reports Created
- Release report: `docs/releases/v3.1.0/features/ml-commons/ml-commons-agent-framework.md`
- Feature report: `docs/features/ml-commons/ml-commons-agent-framework.md` (created)

### Summary
Investigated 18 PRs from the ml-commons repository covering enhancements and bug fixes for the Agent Framework in v3.1.0.

### Key Changes in v3.1.0

**New Features:**
- **Update Agent API** (`PUT /_plugins/_ml/agents/{agent_id}`) - Modify existing agents without re-registration
- **MCP Tools Persistence** - Store MCP tools in system index with update (`POST /_plugins/_ml/mcp/tools/_update`) and list (`GET /_plugins/_ml/mcp/tools/_list`) APIs
- **Function Calling** - Native function calling support for Bedrock/Claude, DeepSeek R1, and OpenAI interfaces via `_llm_interface` parameter
- **Custom SSE Endpoint** - Configurable Server-Sent Events endpoint for MCP client connections
- **Metrics Framework Integration** - Integration with OpenSearch metrics framework for adoption and operational metrics
- **PlanExecuteReflect Memory Tracking** - Return executor_memory_id and executor_parent_interaction_id early to track progress

**Bug Fixes:**
- Fix connector private IP validation when executing agent without remote model (#3862)
- Inline connector name no longer required (#3882)
- Fix AIConnectorHelper tutorial domain_name fetching (#3852)
- Add JSON parsing for nested objects during update query (#3856)
- Add `/` as a valid character (#3854)
- Quick fix for Guava NoClassDefFoundError (#3844)
- Fix Python client MCP server connection (#3822)
- Exclude circuit breaker for Agent execution (#3814)
- Add tenantId to connector executor for inline connectors (#3837)

### Resources Used
- PRs: #3820, #3874, #3888, #3891, #3884, #3810, #3845, #3661, #3786, #3862, #3882, #3852, #3856, #3854, #3844, #3822, #3814, #3837
- Docs: https://docs.opensearch.org/3.0/ml-commons-plugin/api/agent-apis/index/
- Docs: https://docs.opensearch.org/3.0/ml-commons-plugin/agents-tools/agents/plan-execute-reflect/

### PR
- #1010 (merged)
